on:
  push:
    branches:
      - 'main'

jobs:
  publish-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-core
        with:
          paths: packages/core

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-vscode
        with:
          paths: packages/core packages/vscode

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install

      - name: build core
        if: steps.changed-core.outputs.changed == 'true'
        run: npm run build:core

      - name: publish core
        if: steps.changed-core.outputs.changed == 'true'
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/core

      - name: Publish to Visual Studio Marketplace
        if: steps.changed-vscode.outputs.changed == 'true'
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: packages/vscode
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          dependencies: false

      - name: Publish to Open VSX Registry
        if: steps.changed-vscode.outputs.changed == 'true'
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: packages/vscode
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          dependencies: false
